const schema = `
extend type Mutation {
  # Convenience method to create a post with minimal effort.
  createPost(post: PostInput!, options: PostOptions, key: String!): _Discussion 
  # createComment(comment: 
  createComment(comment: CommentInput!, options: PostOptions, key: String): _Discussion
}
  
# Custom Post input
input PostInput {
  author: String!
  body: String!
  tags: [String!]!
  title: String! 
  # Permlink will be autogenerated if omitted. You can provide your own one.
  permlink: String
  json_metadata: String
}

# Custom Post options
input PostOptions {
  allow_curation_rewards: Boolean
  allow_votes: Boolean
  author: String
  extensions: [_ExtensionInput] 
  max_accepted_payout: String
  percent_steem_dollars: Int
  permlink: String
}

# Custom CustomCommentInput
input CommentInput {
  author: String!
  parent_author: String!
  parent_permlink: String!
  body: String!
  # Permlink will be autogenerated if omitted. You can provide your own one.
  permlink: String
  json_metadata: String
}
 `;

module.exports = schema;
